### ISSUE TITLE
Remove org.apache.http dependencies

### ISSUE THREAD

**Issue by dschuermann** [SafeSlingerProject/exchange-android#11]
org.apache.http has been deprecated in SDK 23. Usage should be replaced with UrlConnection classes.

**Comment by mwfarb** [comment]
Indeed! We can do that soon.

**Comment by dschuermann** [comment]
FYI: In our fork, I enabled legacy support to be able to target SDK 23: https://github.com/open-keychain/exchange-android/commit/c7505ec7dec3991a04a9ea85c2506157107a96d5

**Comment by mwfarb** [comment]
I see. Still, it would be nice to be able to remove that dependancy. :-)

**Comment by mwfarb** [comment]
We should be able to get something out within a week.

**Comment by mwfarb** [comment]
Upgraded to HttpsUrlConnection in 510d231.

**Comment by mwfarb** [comment]
@dschuermann You should have all you need in 6014c7497e56ee5a40ad6a2181f4c8e2d98d9c01 now. Let us know if you have any trouble with it. 

This change was included with some pending architectural changes in another branch. We've been creating abstraction layers for making protocol messages flexible enough to run over local wireless scenarios sans servers. I just didn't want the volume of change to scare you. :-)

**Comment by dschuermann** [comment]
@mwfarb Great work! Do I need to upgrade the server component to be compatible with the current git master?

**Comment by mwfarb** [comment]
No, new server code isn't necessary, it's backwards-compatible. 

However, you may want to deploy the latest demo example for your server: https://github.com/SafeSlingerProject/SafeSlinger-AppEngine/tree/master/safeslinger-demo/python. This can be done independently at any time without compromising client experience and without any client changes.

Additions since you last deployed a server version:
- Additional debug logging for developers when app.yaml includes "version: 01060000t".
- (We recommend deploying both as "version: 01060000p" and as "version: 01060000t" with your default version set to the production version naming scheme: "01060000p").
- Our UX testing led us to eliminate digits > 11 on the "lowest number" view so that the conversation between which number of users and which is the lowest number doesn't get out of sync. Example: In a group of 2 users, A says "I've got 3" meaning lowest number, and B enters 3 as the number of users. This way the group size is 2-10 and the lowest number range is 11+ with no overlap.
- We've added the ability to submit server protocol elements as JSON-formatted text so that JavaScript and other languages can also connect. So soon, browser-based PGP Mail like Enigmail and others can use our JS lib to run SafeSlinger and exchange keys with Java users like OKC. More on that soon I hope!
