### ISSUE TITLE
german translation quality?

### ISSUE THREAD

**Issue by Valodim** [SafeSlingerProject/exchange-android#9]
I just skimmed commits and noticed that the transifex pull in 303e570f29a1aef1306c682a84c188e4c3737d46 changed a couple of German strings from an okay-ish translation to google-translate level. I wonder what happened there... anyways I recommend reverting that change, and see if the person who made them is also responsible for other translations.

**Comment by mwfarb** [comment]
Thanks for checking that @Valodim! Sorry about that. We lost some translations due to client/server transifex misconfiguration. I think I fixed it now. Take a look at https://github.com/SafeSlingerProject/exchange-android/commit/06480824c93105a8461e57ab1320b17ddee0759a and let me know if it looks better.

**Comment by Valodim** [comment]
looks ok to me now :+1:
